### ISSUE TITLE
 Sorry for asking a question！

### ISSUE THREAD

**Issue by xianweitudou** [noodlemctwoodle/homeassistant#17]
How to make HKI and dwains coexist on a hass host?

**Comment by noodlemctwoodle** [comment]
@xianweitudou  You need to install Dwains theme using HACS

https://dwainscheeren.github.io/dwains-lovelace-dashboard/getting-started/installation.html

Once you have activated Dwains using HACS then you will be able to run HKI beside it. 

![image](https://user-images.githubusercontent.com/15075388/102881411-b92b0000-4444-11eb-960a-65440ed7acc0.png)

**Comment by xianweitudou** [comment]
thank you very much.

我升级了DD的HACS的 2.0版本，很完美，非常感谢您的addon插件，very perfect,谢谢。
