### ISSUE TITLE
Text of add-on switches no longer visible at light theme

### ISSUE THREAD

**Issue by RubenDijk** [noodlemctwoodle/homeassistant#6]
i've added the ha-monitor more_page to my config. I use the theme of dwains. when i set the theme to light some texts are no longer visible.

Another point when I look at it on my phone it doesn't scale very well. 
Only in the top picture.

I'd also like to give my compliments. keep up the good work!
![Screenshot_20200413-092904_Home_Assistant](https://user-images.githubusercontent.com/18540436/79103931-cea44200-7d6d-11ea-8dcb-48b7a0503151.jpg)

**Comment by noodlemctwoodle** [comment]
All issues fixed in 0.4

![light-theme](https://user-images.githubusercontent.com/15075388/79645096-1d563f80-81a5-11ea-936f-681bde8a86d8.png)
